### ISSUE TITLE
Cluttered file space

### ISSUE THREAD

**Issue by Almost89** [DervexHero/Argon#3]
At the moment file organisation is a bit cluttered and leaves no space for more bits of the project that may come in future (a standalone cli for instance). As a suggestion files could instead be organised a bit like [rojo](https://github.com/rojo-rbx) does. Basically it would just be an organisation which then holds the different bits of the project under there respected repositories e.g.

- Argon (the organisation):
     - plugin (holds the roblox plugin)
     - vscode (holds the vs-code plugin)
     - ???

**Comment by DervexHero** [comment]
Good suggestion! I planned to separate this repo into different repositories but I'm gonna do this later because now I'm very busy.

**Comment by DervexHero** [comment]
Fixed by placing Roblox plugin and VSC extension in [RBLX Plugin](https://github.com/DervexHero/Argon/tree/main/RBLX%20Plugin) and [VSC Extension](https://github.com/DervexHero/Argon/tree/main/VSC%20Extension). I decided not to create a separate organization as it is easier for me to manage one repository and this project is not that big.
